version: '2'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  backend:
    image: com.kirin.ec/backend
    ports: 
      - "8080:8080"
    depends_on: 
      - db
  frontend:
    image: com.kirin.ec/frontend
    ports: 
      - "80:80"
    depends_on: 
      - backend
